In [77]:
import pandas as pd
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data")
df.to_csv('lab2.csv')

In [78]:
#add header
headers=["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","bodystyle","drive-wheels","engine-location","wheel-base","length","width","height","curbweight","engine-type","num-of-cylinders", "engine-size","fuelsystem","bore","stroke","compression-ratio","horsepower", 
"peak-rpm","city-mpg","highway-mpg","price"] 
df.columns=headers
df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'bodystyle', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curbweight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuelsystem', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [79]:
df.head(5)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,bodystyle,drive-wheels,engine-location,wheel-base,...,engine-size,fuelsystem,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [80]:
import numpy as np
df.replace("?", np.nan, inplace = True)
df.head(5)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,bodystyle,drive-wheels,engine-location,wheel-base,...,engine-size,fuelsystem,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [81]:

print("missing values: ", df.isnull().sum().sum())
df.isnull().sum()

missing values:  58

symboling             0
normalized-losses    40
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
bodystyle            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curbweight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuelsystem           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [82]:
l=df.isnull().sum()
l[l>0]

normalized-losses    40
num-of-doors          2
bore                  4
stroke                4
horsepower            2
peak-rpm              2
price                 4
dtype: int64

In [83]:
print(df[df['normalized-losses'].isnull()].index.tolist()[:5])
print(len(df[df['normalized-losses'].isnull()].index.tolist()))

[0, 1, 4, 6, 8]
40

In [84]:
df['normalized-losses'] = pd.to_numeric(df['normalized-losses'], errors='coerce')
df["stroke"] = pd.to_numeric(df["stroke"], errors="coerce")
df["bore"] = pd.to_numeric(df["bore"], errors="coerce")
df["normalized-losses"].fillna(df["normalized-losses"].mean(), inplace=True)
df["stroke"].fillna(df["stroke"].mean(), inplace=True)
df["bore"].fillna(df["bore"].mean(), inplace=True)
df.head(5)
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         2
bodystyle           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curbweight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuelsystem          0
bore                 0
stroke               0
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                4
dtype: int64

In [85]:
df["num-of-doors"]=pd.to_numeric(df["num-of-doors"], errors="coerce")
df["num-of-doors"].fillna(df["num-of-doors"].max(), inplace=True)

In [86]:
#12. Replace the missing values in “horse_power”,peak_rpm with the values in the next row. 
#If the last row also contains missing values, replace them with the values in the previous row.
df["horsepower"]=pd.to_numeric(df["horsepower"], errors="coerce")
df["peak-rpm"]=pd.to_numeric(df["peak-rpm"], errors="coerce")
df["horsepower"].fillna(method='bfill', inplace=True)
df["peak-rpm"].fillna(method='bfill', inplace=True)
df.head(5)

/tmp/ipykernel_219333/2891247055.py:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["horsepower"].fillna(method='bfill', inplace=True)
/tmp/ipykernel_219333/2891247055.py:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["peak-rpm"].fillna(method='bfill', inplace=True)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,bodystyle,drive-wheels,engine-location,wheel-base,...,engine-size,fuelsystem,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,std,NaN,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500
1,1,122.0,alfa-romero,gas,std,NaN,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500
2,2,164.0,audi,gas,std,NaN,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950
3,2,164.0,audi,gas,std,NaN,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450
4,2,122.0,audi,gas,std,NaN,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,15250

In [87]:
df["price"].dropna()

0      16500
1      16500
2      13950
3      17450
4      15250
       ...
199    16845
200    19045
201    21485
202    22470
203    22625
Name: price, Length: 200, dtype: object

In [88]:

df.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
aspiration            object
num-of-doors         float64
bodystyle            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curbweight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuelsystem           object
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object